# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\上位机\8路继电器\comQT\ui\comwinodow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt 
from PyQt5.QtGui import QMovie,  QIcon,  QPixmap,  QPalette

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(510, 548)
        MainWindow.setWindowIcon(QIcon('./icon/com.ico')) #设置图标
        #禁止拉伸窗口大小  
        MainWindow.setFixedSize(MainWindow.width(), MainWindow.height());   
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 241, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 120, 171))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_7)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("波特率:")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.comboBox_8 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_8)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.comboBox_9 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_9)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.comboBox_10 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_10)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.label)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setPlaceholderText("1-63")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget)
        self.label_53.setObjectName("label_53")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 81, 61))
        self.label_2.setObjectName("label_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(150, 80, 77, 112))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout.addWidget(self.pushButton_20)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 10, 241, 181))
        self.groupBox.setObjectName("groupBox")
        self.lable_57 = QtWidgets.QLabel(self.groupBox)
        self.lable_57.setGeometry(QtCore.QRect(11, 20, 221, 151))
        self.lable_57.setObjectName("lable_57")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 220, 221, 131))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 201, 101))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 3, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 4, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 1, 4, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 2, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 2, 4, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 2, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 3, 1, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 3, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 3, 3, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 3, 4, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 3, 5, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 360, 221, 101))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 70, 201, 25))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.spinBox_5 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_5.setObjectName("spinBox_5")
        self.horizontalLayout_2.addWidget(self.spinBox_5)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_2.addWidget(self.label_18)
        self.spinBox_6 = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spinBox_6.setObjectName("spinBox_6")
        self.horizontalLayout_2.addWidget(self.spinBox_6)
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_2.addWidget(self.pushButton_22)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 30, 201, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout.addWidget(self.spinBox_4)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout.addWidget(self.spinBox_3)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget4)
        self.pushButton_21.setObjectName("pushButton_21")
        self.horizontalLayout.addWidget(self.pushButton_21)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(250, 210, 251, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 231, 95))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 0, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_29.setObjectName("label_29")
        self.gridLayout_2.addWidget(self.label_29, 0, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 0, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_2.addWidget(self.label_33, 0, 3, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_30.setObjectName("label_30")
        self.gridLayout_2.addWidget(self.label_30, 1, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 1, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_2.addWidget(self.label_34, 1, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_31.setObjectName("label_31")
        self.gridLayout_2.addWidget(self.label_31, 2, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 2, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_2.addWidget(self.label_32, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 3, 2, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 3, 3, 1, 1)

        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(250, 340, 251, 121))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 231, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_37.setObjectName("label_37")
        self.gridLayout_3.addWidget(self.label_37, 0, 0, 1, 1)

        self.label_38 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_38.setObjectName("label_38")
        self.gridLayout_3.addWidget(self.label_38, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 0, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_40.setObjectName("label_40")
        self.gridLayout_3.addWidget(self.label_40, 0, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_3.addWidget(self.label_41, 1, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_3.addWidget(self.label_42, 1, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_3.addWidget(self.label_43, 1, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_3.addWidget(self.label_44, 1, 3, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_3.addWidget(self.label_45, 2, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_3.addWidget(self.label_46, 2, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_3.addWidget(self.label_47, 2, 2, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_3.addWidget(self.label_48, 2, 3, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_49.setObjectName("label_49")
        self.gridLayout_3.addWidget(self.label_49, 3, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_50.setObjectName("label_50")
        self.gridLayout_3.addWidget(self.label_50, 3, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_51.setObjectName("label_51")
        self.gridLayout_3.addWidget(self.label_51, 3, 2, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_52.setObjectName("label_52")
        self.gridLayout_3.addWidget(self.label_52, 3, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setObjectName("label_54")
        self.label_54.setGeometry(10, 480, 95, 30)  
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_23.setGeometry(126, 485, 25, 25) 
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(100, 485, 25, 25)
        self.pushButton_25.setObjectName("pushButton_25")

        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(160, 470, 341, 41))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_55 = QtWidgets.QLabel(self.groupBox_4)
        self.label_55.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_55.setObjectName("label_55")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox.setGeometry(QtCore.QRect(90, 15, 41, 22))
        self.spinBox.setObjectName("spinBox")
        self.label_56 = QtWidgets.QLabel(self.groupBox_4)
        self.label_56.setGeometry(QtCore.QRect(140, 20, 41, 16))
        self.label_56.setObjectName("label_56")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_2.setGeometry(QtCore.QRect(180, 15, 42, 22))
        self.spinBox_2.setObjectName("spinBox_2")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_24.setGeometry(QtCore.QRect(230, 15, 100, 23))
        self.pushButton_24.setObjectName("pushButton_24")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 510, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        
        self.retranslateUi(MainWindow)
        #self.pushButton.setChecked(False)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "8路继电器上位机"))
        self.groupBox_2.setTitle(_translate("MainWindow", "COM口设置"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">端口号:</span></p></body></html>"))
        self.label_6.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_6.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">波特率:</span></p></body></html>"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "110"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "300"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "600"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "1200"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "2400"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "4800"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "9600"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "14400"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "19200"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "38400"))
        self.comboBox_6.setItemText(10, _translate("MainWindow", "56000"))
        self.comboBox_6.setItemText(11, _translate("MainWindow", "57600"))
        self.comboBox_6.setItemText(12, _translate("MainWindow", "115200"))
        self.comboBox_6.setItemText(13, _translate("MainWindow", "128000"))
        self.comboBox_6.setItemText(14, _translate("MainWindow", "230400"))
        self.comboBox_6.setItemText(15, _translate("MainWindow", "256000"))
        self.comboBox_6.setItemText(16, _translate("MainWindow", "460800"))
        self.comboBox_6.setItemText(17, _translate("MainWindow", "500000"))
        self.comboBox_6.setItemText(18, _translate("MainWindow", "512000"))
        self.comboBox_6.setItemText(19, _translate("MainWindow", "600000"))
        self.comboBox_6.setItemText(20, _translate("MainWindow", "750000"))
        self.comboBox_6.setItemText(21, _translate("MainWindow", "921600"))
        self.comboBox_6.setItemText(22, _translate("MainWindow", "1000000"))
        self.comboBox_6.setItemText(23, _translate("MainWindow", "1500000"))
        self.comboBox_6.setItemText(24, _translate("MainWindow", "2000000"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "COM1"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "COM2"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "COM3"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "COM4"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "COM5"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "COM6"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "COM7"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "COM8"))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "COM9"))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "COM10"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">数据位:</span></p></body></html>"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "8"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "7"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "6"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">校验位:</span></p></body></html>"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "N"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "E"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "O"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "M"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "S"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">停止位:</span></p></body></html>"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "1.5"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "2"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">串口状态</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">状态:</span></p></body></html>"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">地址:</span></p></body></html>"))
        #self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.movie = QMovie("./icon/cat.gif") #设置gif图标
        self.label_2.setMovie(self.movie)
        self.movie.start()
        self.pushButton_6.setText(_translate("MainWindow", "检测串口"))
        self.pushButton_4.setIcon(QIcon(QPixmap("./icon/switch-on-icon.png")))
        self.pushButton_4.setText(_translate("MainWindow", "开启"))
        self.pushButton_5.setIcon(QIcon(QPixmap("./icon/switch-off-icon.png")))
        self.pushButton_5.setText(_translate("MainWindow", "关闭"))
        self.pushButton_20.setText(_translate("MainWindow", "更换播放区"))
        self.groupBox.setTitle(_translate("MainWindow", "播放区"))
        self.groupBox_3.setTitle(_translate("MainWindow", "单个继电器控制"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">00:</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "开"))
        self.pushButton_2.setText(_translate("MainWindow", "关"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">01:</span></p></body></html>"))
        self.pushButton_7.setText(_translate("MainWindow", "开"))
        self.pushButton_3.setText(_translate("MainWindow", "关"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">02:</span></p></body></html>"))
        self.pushButton_9.setText(_translate("MainWindow", "开"))
        self.pushButton_8.setText(_translate("MainWindow", "关"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">03:</span></p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "开"))
        self.pushButton_10.setText(_translate("MainWindow", "关"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">04:</span></p></body></html>"))
        self.pushButton_13.setText(_translate("MainWindow", "开"))
        self.pushButton_12.setText(_translate("MainWindow", "关"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">05:</span></p></body></html>"))
        self.pushButton_15.setText(_translate("MainWindow", "开"))
        self.pushButton_14.setText(_translate("MainWindow", "关"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">06:</span></p></body></html>"))
        self.pushButton_17.setText(_translate("MainWindow", "开"))
        self.pushButton_16.setText(_translate("MainWindow", "关"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">07:</span></p></body></html>"))
        self.pushButton_19.setText(_translate("MainWindow", "开"))
        self.pushButton_18.setText(_translate("MainWindow", "关"))
        self.groupBox_6.setTitle(_translate("MainWindow", "多个继电器控制"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">关闭:</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "--"))
        self.pushButton_22.setText(_translate("MainWindow", "关闭"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">打开:</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "--"))
        self.pushButton_21.setText(_translate("MainWindow", "开启"))
        self.groupBox_5.setTitle(_translate("MainWindow", "继电器状态"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">00:</span></p></body></html>"))
        self.label_29.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">01:</span></p></body></html>"))
        self.label_33.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">02:</span></p></body></html>"))
        self.label_30.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">03:</span></p></body></html>"))
        self.label_34.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">04:</span></p></body></html>"))
        self.label_31.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">05:</span></p></body></html>"))
        self.label_35.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">06:</span></p></body></html>"))
        self.label_32.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">07:</span></p></body></html>"))
        self.label_36.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.groupBox_7.setTitle(_translate("MainWindow", "光耦状态"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">00:</span></p></body></html>"))
        self.label_38.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">01:</span></p></body></html>"))
        self.label_40.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">02:</span></p></body></html>"))
        self.label_42.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">03:</span></p></body></html>"))
        self.label_44.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">04:</span></p></body></html>"))
        self.label_46.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">05:</span></p></body></html>"))
        self.label_48.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_49.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">06:</span></p></body></html>"))
        self.label_50.setPixmap(QPixmap('./icon/OFF.jpg')) 
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">07:</span></p></body></html>"))
        self.label_52.setPixmap(QPixmap('./icon/OFF.jpg')) 

        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; vertical-align:sub;\">扫描--关闭:</span></p></body></html>"))
        self.pushButton_23.setIcon(QIcon(QPixmap("./icon/saooff.jpg")))
        self.pushButton_23.setToolTip('<b>关闭扫描</b>')
        self.pushButton_25.setIcon(QIcon(QPixmap("./icon/saomiao.jpg")))
        self.pushButton_25.setToolTip('<b>打开扫描</b>')

        self.groupBox_4.setTitle(_translate("MainWindow", "写寄存器"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">寄存器地址:</span></p></body></html>"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">功能:</span></p></body></html>"))
        self.pushButton_24.setIcon(QIcon(QPixmap("./icon/redo.png")))
        self.pushButton_24.setText("写入寄存器")

        self.movie_1 = QMovie("./icon/zzp.jpg") #设置gif图标
        self.lable_57.setMovie(self.movie_1)
        self.movie_1.start()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

